[build]
builder = "RAILPACK"
buildCommand = "PRISMA_SKIP_POSTINSTALL_GENERATE=true NPM_CONFIG_REGISTRY=https://registry.npmjs.org npm install && NPM_CONFIG_REGISTRY=https://registry.npmjs.org npx prisma generate && npx prisma migrate deploy && npm run build"
watchPatterns = ["/backend/**"]

[deploy]
startCommand = "node dist/index.js"
healthcheckPath = "/healthz"
healthcheckTimeout = 120
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
